# Generated by Django 6.1.1 on 2026-09-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_bandana_collar_leash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandana',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='collar',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='leash',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shampoo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
